Задание 1

In [ ]:
import numpy as np

In [26]:
a_mas=np.array([[1, 6],[2, 8],[3, 11],[3, 10],[1, 7]]) 

In [7]:
a_mas.shape

(5, 2)

In [20]:
a_mas

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [27]:
a_mas1 = np.mean(a_mas, axis = 0)

In [28]:
a_mas1

array([2. , 8.4])

Задание 2

In [30]:
a_centered = a_mas - a_mas1

In [31]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [ ]:
Задание 3

In [45]:
a_centered_sp = np.dot(a_centered[:,0] ,  a_centered[:, 1])

In [47]:
a_centered_sp

8.0

In [49]:
a_centered_sp = np.inner(a_centered[:,0] ,  a_centered[:, 1])
a_centered_sp

8.0

In [50]:
a_centered_sp = np.sum((a_centered[:,0]) *  (a_centered[:, 1]))
a_centered_sp

8.0

In [80]:
a_centered_sp = np.tensordot(a_centered[:,0] ,  a_centered[:, 1], axes=(-1,-1))
a_centered_sp

array(8.)

In [76]:
rows, columns = a_centered.shape
rows

5

In [81]:
a_centered_sp = a_centered_sp / (rows-1)
a_centered_sp

2.0

Задание 4**

In [87]:
a_mas2 = a_mas.transpose()
a_mas2

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [89]:
a_mas2_cor=np.cov(a_mas2)
a_mas2_cor


array([[1. , 2. ],
       [2. , 4.3]])

или без транспонирование сразу через индексы

In [92]:
a_mas3_cor=np.cov(a_mas[:,0],a_mas[:,1])
a_mas3_cor

array([[1. , 2. ],
       [2. , 4.3]])

Работа с Pandas

Задание 1

In [161]:
import pandas as pd

In [162]:
data = {'author_id' : [1, 2, 3], 
        'author_name' : ['Тургенев', 'Чехов', 'Островский']}
data
         

{'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}

In [163]:
authors = pd.DataFrame(data)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [164]:
data_2 = {'author_id' : [1, 1, 1, 2, 2, 3, 3], 
        'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
         'price' : [450, 300, 350, 500, 450, 370, 290]}
data_2

{'author_id': [1, 1, 1, 2, 2, 3, 3],
 'book_title': ['Отцы и дети',
  'Рудин',
  'Дворянское гнездо',
  'Толстый и тонкий',
  'Дама с собачкой',
  'Гроза',
  'Таланты и поклонники'],
 'price': [450, 300, 350, 500, 450, 370, 290]}

In [165]:
book = pd.DataFrame(data_2)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2


In [185]:
 authors_price = pd.merge(authors, book)
 authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [186]:
top5 = authors_price.sort_values(by = ['price'], ascending = False) 
top5

author_id author_name            book_title  price
3          2       Чехов      Толстый и тонкий    500
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
2          1    Тургенев     Дворянское гнездо    350
1          1    Тургенев                 Рудин    300
6          3  Островский  Таланты и поклонники    290

In [187]:
authors_price = top5[0:5]
authors_price

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

In [254]:
a_min_price=authors_price.groupby(['author_name'])['price'].min()
a_min_price

author_name
Островский    370
Тургенев      350
Чехов         450
Name: price, dtype: int64

In [255]:
b_max_price=authors_price.groupby(['author_name'])['price'].max()
b_max_price

author_name
Островский    370
Тургенев      450
Чехов         500
Name: price, dtype: int64

In [258]:
c_mean_price=authors_price.groupby(['author_name'])['price'].mean()
c_mean_price

author_name
Островский    370.0
Тургенев      400.0
Чехов         475.0
Name: price, dtype: float64

In [257]:
authors_stat = (pd.concat([ a, c, b], axis=1, keys=["min_price", "max_price", "mean_price"]))
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         370        370       370.0
Тургенев           350        450       400.0
Чехов              450        500       475.0


Задание 5**

In [276]:
import numpy as np

In [260]:
authors_price = pd.merge(authors, book)
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [261]:
authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [280]:
book_info=pd.pivot_table(authors_price, index=['author_name', 'cover'], values = ['price'], aggfunc=np.sum)
book_info

price
author_name cover         
Островский  мягкая     660
Тургенев    мягкая     650
            твердая    450
Чехов       твердая    950

In [281]:
import pickle

In [283]:
with open('book_info.pkl', 'wb') as pickle_out:
    pickle.dump(book_info, pickle_out)

In [286]:
with open('book_info.pkl', 'rb') as pickle_in:
    book_info2 = pickle.load(pickle_in)


In [287]:
book_info2

price
author_name cover         
Островский  мягкая     660
Тургенев    мягкая     650
            твердая    450
Чехов       твердая    950